services:
  client:
    build: 
      context: ./client/
      dockerfile: Dockerfile
    image: video_app_ui
    ports: 
      - "3000:3000"
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    image: video_app_api
    ports:
      - "8000:8000"